var con =  require('./connection');
const bodyParser = require('body-parser');
const crypto = require('crypto');
const nodemailer = require('nodemailer');
const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: 'evotingproject2080@gmail.com',
    pass: 'tothdngbgmmiswxb'
  }
});

var express = require('express');
var bcrypt = require('bcrypt');
const saltRounds = 10;

var app = express();

app.use(bodyParser.json());
app.use("/assets",express.static("assets"));
app.use(bodyParser.urlencoded({extended: true}));
app.get('/',function(req,res)
{
    res.sendFile(__dirname+'/register.html')

});
app.post('/',function(req,res){
var firstname = req.body.firstName;
var middlename = req.body.middleName;
var lastname = req.body.lastName;
var NID = req.body.nationalId;
var emaill = req.body.email;
var PN = req.body.phoneNumber;
var PW = generateRandomPassword(10);
console.log('Pass:',PW);

 bcrypt.hash(PW, saltRounds, function(err, hash) {
    if (err) throw err;
    con.connect(function(error) {
      if (error) throw error;
      var sql = "INSERT INTO users(first_name,middle_name,last_name,national_id,email,phone_number,password) VALUES ('" + firstname + "','" + middlename + "','" + lastname + "','" + NID + "','" + emaill + "','" + PN + "','" + hash + "')";
      con.query(sql, function(error, result) {
        if (error) throw error;
        res.send('RECORD SUCCESSFULL' + console.log("success"));
      });
    });
  });
  const mailOptions = {
    from: 'evotingproject2080@gmail.com',
    to: emaill,
    subject: 'E-voting security alert',
    text: `Dear ${firstname}, 
    We hope this email finds you well. As a user of E-voting site, we are writing to provide you with a new password to access the E-voting website. This password is needed for you to securely access through and use the features of the app.
    Your password is as follows:
    password : ${PW}
    Please note that this password is automatically generated by our system.
    Thank you for using E-voting.
    Best regards,

    E-voting Project
    evotingproject2080@gmail.com
    `
  };
  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.log(error);
      res.status(500).send('Error sending email');
    } else {
      console.log('Email sent: ' + info.response);
      res.send('Password reset email sent');
    }
  });
});
app.listen(5501);
function generateRandomPassword(length) {
  return crypto.randomBytes(Math.ceil(length/2))
          .toString('hex')
          .slice(0,length);
}